"use client";

import Provider from "./provider";
import Head from "next/head";
import { GlobalContextProvider } from '@/context/Globals';
import { Flex } from "@chakra-ui/react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <Head>
        <title>wPOKT Staking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Provider>
        <GlobalContextProvider>
            <Flex justify="center" align="center" flexDir={'column'} bg={'#09090B'} minH={'100vh'} justifyContent={'space-between'} width={'100vw'} gap={4}>
            <Navigation />
          {children}
          <Footer/>
          </Flex>
          </GlobalContextProvider>
          </Provider>
      </body>
    </html>
  );
}
